"""add pending_reply_task_id to sessions

Revision ID: 4522b2be2830
Revises: 532f73a4ef44
Create Date: 2026-06-05 21:32:17.531901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4522b2be2830'
down_revision: Union[str, Sequence[str], None] = '532f73a4ef44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pending_reply_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'pending_reply_task_id')
    # ### end Alembic commands ###
