"""store compliance: ai consent, ai reports, user deleted_at

Revision ID: 637a013479e3
Revises: 14a1d4e44497
Create Date: 2026-10-08 08:57:50.261819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637a013479e3'
down_revision: Union[str, Sequence[str], None] = '14a1d4e44497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_consents_user_id_version', 'ai_consents', ['user_id', 'version'], unique=False)
    op.create_index('uq_ai_consents_active_user_version', 'ai_consents', ['user_id', 'version'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('ai_response_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('harmful', 'inappropriate', 'inaccurate', 'out_of_character', 'other', name='ai_report_reason'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='ai_report_status'), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'message_id', name='uq_ai_reports_reporter_message')
    )
    op.create_index('ix_ai_reports_session_id', 'ai_response_reports', ['session_id'], unique=False)
    op.create_index('ix_ai_reports_status_created_at', 'ai_response_reports', ['status', 'created_at'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_index('ix_ai_reports_status_created_at', table_name='ai_response_reports')
    op.drop_index('ix_ai_reports_session_id', table_name='ai_response_reports')
    op.drop_table('ai_response_reports')
    op.drop_index('uq_ai_consents_active_user_version', table_name='ai_consents', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_ai_consents_user_id_version', table_name='ai_consents')
    op.drop_table('ai_consents')
    # ### end Alembic commands ###
    # drop_table doesn't drop the Postgres enum types; without this a re-upgrade fails.
    sa.Enum(name='ai_report_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ai_report_reason').drop(op.get_bind(), checkfirst=True)
