"""week15: notification prefs + analytics indexes

Revision ID: 7892262555f3
Revises: 281389d4934f
Create Date: 2026-06-28 21:13:23.088361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7892262555f3'
down_revision: Union[str, Sequence[str], None] = '281389d4934f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_diseases_unit_id', 'diseases', ['unit_id'], unique=False)
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_index('ix_sessions_course_id_status', 'sessions', ['course_id', 'status'], unique=False)
    op.create_index('ix_sessions_user_id_course_id', 'sessions', ['user_id', 'course_id'], unique=False)
    op.add_column('users', sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('quiet_hours_start', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('quiet_hours_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quiet_hours_end')
    op.drop_column('users', 'quiet_hours_start')
    op.drop_column('users', 'push_enabled')
    op.drop_index('ix_sessions_user_id_course_id', table_name='sessions')
    op.drop_index('ix_sessions_course_id_status', table_name='sessions')
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_index('ix_diseases_unit_id', table_name='diseases')
    # ### end Alembic commands ###
