"""replace_netid_with_google_uid

Revision ID: aab0c0019f65
Revises: 47c247aa271f
Create Date: 2026-05-17 20:13:33.877639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab0c0019f65'
down_revision: Union[str, Sequence[str], None] = '47c247aa271f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_uid', sa.String(length=128), nullable=False))
    op.drop_constraint(op.f('users_netid_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['google_uid'])
    op.drop_column('users', 'netid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('netid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_netid_key'), 'users', ['netid'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'google_uid')
    # ### end Alembic commands ###
